config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants
  resources :menus
  get 'order/myorder'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
	belongs_to :restaurant
	#belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	has_many :menus, dependent: :destroy
	#belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         #has_many :restaurants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
	def index
		@menus = Menu.all
	end

	def show
	end

	def new
		@menu = Menu.new
	end

	def create
		@menu = Menu.new(name: params[:menu][:name], restaurant_id: params[:menu][:restaurant_id], quantity: params[:menu][:quantity], price: params[:menu][:price])
		@menu.save
		redirect_to root_path
	end

	private

	def set_menu
		@menu = Menu.find(params[:id])
	end

	def menu_params
		params.fetch(:menu).permit(:name, :quantity, :price)
	end

end

app/controllers/order_controller.rb
class OrderController < ApplicationController

	def myorder
	 OrderMailer.order_created(current_user).deliver_now
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    #byebug
    @restaurants = Restaurant.all
    #@restaurants = @restaurants.find_by(id: user.id)
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    #byebug
    @restaurant = Restaurant.find_by(id: params[:id])
    #@restaurant = Restaurant
    @menu = @restaurant.menus
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.fetch(:restaurant).permit(:name, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Order</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style>
* {box-sizing: border-box;}

body { 
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.header {
  overflow: hidden;
  background-color: #f1f1f1;
  padding: 20px 10px;
}

.header a {
  float: left;
  color: black;
  text-align: center;
  padding: 12px;
  text-decoration: none;
  font-size: 18px; 
  line-height: 25px;
  border-radius: 4px;
}

.header a.logo {
  font-size: 25px;
  font-weight: bold;
}

.header a:hover {
  background-color: #ddd;
  color: black;
}

.header a.active {
  background-color: dodgerblue;
  color: white;
}

.header-right {
  float: right;
}

@media screen and (max-width: 500px) {
  .header a {
    float: none;
    display: block;
    text-align: left;
  }
  
  .header-right {
    float: none;
  }
}
</style>
</head>
<body>

<div class="header">
  <a href="#default" class="logo">Restaurants</a>
  <div class="header-right">
    <a class="active" href="/restaurants">All Restaurants</a>
  </div>
</div>


  <% if user_signed_in? %>

    Signed in as <%= current_user.email %>.
  Not you?

    <%= link_to "Sign out",
  destroy_user_session_path, :method => :delete %>

  <% else %>

    <%= link_to "Sign up",
  new_user_registration_path %> or <%= link_to "sign in",
  new_user_session_path %>

  <% end %>  

  <body>
    <%= yield %>
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_with(model: menu, local: true) do |form| %>
   <p>
    <%= form.label :Menu_item %><br>
    <%= form.text_field :name %>
  </p>
   <p>
    <%= form.label :Price %><br>
    <%= form.text_field :price %>
  </p>
   <p>
    <%= form.label :Quantity %><br>
    <%= form.text_field :quantity %>
  </p>
  <p>
    <br>
     <%= form.select :restaurant_id, Restaurant.all.map{|m| [m.name, m.id] },{prompt: "Please select Restaurant"}, class: "form-control" %>
  </p>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menu</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <!-- <tbody>
    <%# @menu.each do |menu| %>
      <tr>
        <td><%#= menu.name %>
        <td><%#= link_to 'Show', menu %></td>
        <td><%#= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%#= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody> -->
</table>

<br>

<%= link_to 'Create New Menu', new_menu_path, :class => "btn btn-info btn-sm" %><br>
<%= link_to 'Back', restaurants_path, class:"btn btn-success btn-sm" %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path, class:"btn btn-info btn-sm" %>

app/views/order/myorder.html.erb
<h1>hii!  Your order created successfully </h1>

<%= link_to 'Back', restaurants_path%>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
   <p>
    <%= form.label :Name_of_the_restaurant %><br>
    <%= form.text_field :name %>
  </p>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant, class:"btn btn-info btn-sm" %> |
<%= link_to 'Back', restaurants_path, class:"btn btn-success btn-sm" %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<!-- <h1>Restaurants</h1> -->

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each_with_index do |restaurant, index| %>
      <tr>
        <td><%= index + 1 %>.&nbsp;</td>
        <td><%= restaurant.name %>
        <td><%= link_to 'Show', restaurant, class:"btn btn-success btn-sm" %>|</td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class:"btn btn-primary btn-sm" %>|</td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Menu', new_menu_path, class:"btn btn-success btn-sm" %> |

<%= link_to 'New Restaurant', new_restaurant_path, :class => "btn btn-info btn-sm" %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Name Of Restaurant</h3>
<%= @restaurant.name %>


<%= link_to 'Edit', edit_restaurant_path(@restaurant), class:"btn btn-primary btn-sm" %> |
<%= link_to 'Back', restaurants_path, class:"btn btn-info btn-sm" %><br><br>


<h3> Menu </h3>
<% @menu.each_with_index do |menus, index| %>
	<p>
	  <strong>S.No.:</strong>
			<%= index + 1 %>
	<!-- </p>
	<p>	 -->
	<strong>Name </strong>
	<%= menus.name %>
	<!-- </p>

	<p> -->
	<strong>Price</strong>
	<%= menus.price %>
	<!-- </p>

	<p> -->
	<strong>Quantity</strong>
	<%= menus.quantity %>
	<%= link_to 'Place Order', order_myorder_path, class:"btn btn-success btn-sm" %>
	</p>
	
	
<% end %>